---
layout: cv
title: Seth Chen's Resume
---
# Seth Chen


<div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>

## Education

__brigham Young University-Idaho__`2022-Present`
- BS Computer Science - Data Scinece | Software Design Certificate
- GPA: 3.91
- Data Science Group Member | BYU-I Data Science Society.

## Skills
- C++
- Python
- SQL

## Academic Projects
- Implemented <a href = "https://github.com/sethchens/ApolloSimulator1">Apollo Lander Simulator</a> and <a href = "https://github.com/sethchens/Artillery-Simulator">Artillery Simulator</a>, concentrated on requirement elicitation skills, pair programming skills, and applying related physics.
- Assisted 1 professor's research at BYU-I, focused on finding recommendations for program modularization for people at different levels.


<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) -->

### Work Experience
#### BYU-I System & Innovation`May 2023-Present`
##### Technology Specailist
- Retrieved necessary data from Canvas API to Google Sheets by writing 10 optimized and reusable Google Appscript codes to handle requests from course builders.  
- Brought all data and processes into one place by building 1 Canvas App to simplify office's hiring process.  
- Kept up continuing personal value in the team by setting and following up weekly goals to bring value, leading to a constantly growing team.  
- Socialized within the team by attending 10 team activities to build up relationships and trust.

#### BYU-I Technology Support`July 2022-December 2022`  
##### Technician
- Simplified complex working flow by communicating with the team and documenting details of each ticket to handle various technical requests around campus, leading to better teamwork proficiency.  
- Provided 55 customers personalized assistance by offering available timeframe and observing what might be needed while calling.  
- Conducted testing procedures created by former technicians and developed new ones based on personal experience to troubleshoot computers and peripherals.  
<!-- ### Footer

Last updated: May 2013 -->